- name: install apache package with PHP support
  tags: apache, web
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: change e-mail address for server admin
  tags: centos, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: copy default html file
  tags: apache, web
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
