- name: add ssh key for ansible-node user
  tags: always
  authorized_key:
    user: ansible-node
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhYkZrtCu9EBXt4neMfAPWdOK7rpSQVuIT8qFI59lip Connection for Ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
